name: Python package

on:
  push:
    branches: [ main ]

jobs:  # job : 단일 가상 환경 
  build:  # job ID : 문자, -(대시), _(언더바)로 구성

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        mongodb-version: ['4.2', '4.4']

    steps:  # 순차적으로 실행되는 프로세스 단위 
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        sudo apt-get install -y mongodb-org redis-server
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
